
logo: AHMED'S WORLD
title: Ahmed world is a portfolio site
start_year: 2023
current_year: { { site.time | date: "%Y" } }
address: 43 Raymouth Rd. Baltemoer, London 3910
email: ahmedsharifkhannoor@gmail.com
phone: +8801744750096 
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

facebook_username: https://www.facebook.com/ahmedsharifkhannoor
twitter_username: https://www.twitter.com/maxnoor87
instagram_username: https://www.instagram.com/ahmedsharifkhannoor
linkedin_username: https://www.linkedin.com/in/ahmedsharifkhannoor
behance_username: https://www.behance.net/ahmedsharifkhannoor
dribbble_username: https://dribbble.com/ahmedsharifkhannoor
pinterest_username: https://ar.pinterest.com/ahmedsharifkhannoor/
web_username: https://ahmedsharifkhannoor.blogspot.com/
globe_username: https://designtgg.blogspot.com/
person_username: https://bio.site/ahmedsharifkhannoor
github_username: https://www.github.com/ahmedsharifkhan
youtube_username: https://www.youtube.com/channel/UCBfIS1RdIpSoS1e75LXJuxw

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"

  - scope:
      path: ""
      type: categories
    values:
      permalink: /categories/:name/



paginate: 5 # or the number of posts you want per page

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/

header_pages:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Portfolio
    url: /portfolio
  - title: Noor
    url: /noor

google_analytics_id: G-W5KN8DPXQ9
facebook_pixel_id: 1234567890

gems:
  - jekyll-sitemap
# exclude:
#   - excluded-page.html


# Build settings
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-feed



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# host: 0.0.0.0
# port: 4000

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

include: ["_pages"]

# Pagination 
paginate: 6
paginate_path: /page:num/


# Other
# markdown: kramdown

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true